"""Modular, deterministic migration planning from canonical project evidence."""

from __future__ import annotations

from migrator.cir import CanonicalIR
from migrator.models import (
    CapabilityAssessment,
    MigrationBlueprint,
    MigrationUnit,
    MigrationWave,
    WesleyAssessment,
)


def _strategy(wesley: WesleyAssessment, cir: CanonicalIR) -> str:
    if wesley.overall_classification == "retain":
        return "analysis-only"
    if wesley.overall_classification == "reengineer":
        return "strangler-migration"
    if not cir.behaviors and not cir.entities:
        return "static-extraction"
    return "visual-rebuild-and-strangler-migration"


def _capabilities(cir: CanonicalIR) -> list[CapabilityAssessment]:
    behavior_kinds = {unit.unit_id.removeprefix("behavior:") for unit in cir.behaviors}
    capabilities = [
        CapabilityAssessment(capability="routes", status="supported", evidence=["CIR route candidates"] if cir.routes else ["no routes observed"]),
        CapabilityAssessment(capability="templates-and-layout", status="supported", evidence=["source adapter route and template evidence"]),
        CapabilityAssessment(capability="static-assets", status="supported", evidence=["CIR asset inventory"]),
        CapabilityAssessment(capability="content-extraction", status="supported", evidence=["bounded source context"]),
        CapabilityAssessment(
            capability="database-schema-analysis",
            status="partial" if cir.entities else "unsupported",
            evidence=["CIR entities"] if cir.entities else ["no database entities observed"],
        ),
        CapabilityAssessment(
            capability="database-behavior-migration",
            status="manual" if "database-reads-or-writes" in behavior_kinds else "unsupported",
            evidence=["database behavior requires a target data service"] if "database-reads-or-writes" in behavior_kinds else [],
        ),
        CapabilityAssessment(
            capability="authentication",
            status="manual" if any("session" in kind or "auth" in kind for kind in behavior_kinds) else "unsupported",
            evidence=["authentication behavior is not generated by this target profile"] if any("session" in kind or "auth" in kind for kind in behavior_kinds) else [],
        ),
        CapabilityAssessment(
            capability="forms-and-email",
            status="manual" if any("form" in kind or "email" in kind for kind in behavior_kinds) else "unsupported",
            evidence=["form delivery requires an approved backend or provider"] if any("form" in kind or "email" in kind for kind in behavior_kinds) else [],
        ),
    ]
    return capabilities


def _unit_for_behavior(unit_id: str, classification: str) -> MigrationUnit:
    label = unit_id.removeprefix("behavior:").replace("-", " ")
    manual = classification in {"reengineer", "replace", "coexist"}
    return MigrationUnit(
        unit_id=unit_id,
        source_scope=label,
        classification=classification,
        action="reengineer behavior" if manual else "migrate behavior",
        target_scope=f"target behavior: {label}",
        preserved_behavior=[] if manual else [label],
        unsupported_behavior=["backend implementation requires human engineering"] if manual else [],
        risks=["behavioral parity is not established by static inspection"],
        validation_gates=["human behavior review", "target integration test"],
        coexistence_required=classification in {"coexist", "reengineer"},
    )


def build_migration_blueprint(cir: CanonicalIR, wesley: WesleyAssessment) -> MigrationBlueprint:
    """Build the migration roadmap without an LLM or target code generation."""
    classification = wesley.overall_classification
    units: list[MigrationUnit] = [
        MigrationUnit(
            unit_id="assets",
            source_scope="static assets",
            classification="retain",
            action="copy assets",
            target_scope="public/legacy",
            validation_gates=["asset existence check"],
        ),
    ]
    units.extend(
        MigrationUnit(
            unit_id=f"route:{route.route_id}",
            source_scope=route.pattern,
            classification="migrate" if classification != "retain" else "retain",
            action="recreate route in target stack",
            target_scope=f"Next.js route {route.pattern}",
            dependencies=["assets"],
            preserved_behavior=["route and visible content"],
            risks=["route behavior is inferred from static evidence"],
            validation_gates=["route check", "visual review"],
        )
        for route in cir.routes
    )
    units.extend(
        _unit_for_behavior(unit.unit_id, "reengineer" if classification in {"reengineer", "coexist"} else "evolve")
        for unit in cir.behaviors
    )
    if cir.entities:
        units.append(MigrationUnit(
            unit_id="data-model",
            source_scope="database schema and access",
            classification="replace",
            action="map schema and replace data access",
            target_scope="approved target data service",
            dependencies=[unit.unit_id for unit in units if unit.unit_id.startswith("behavior:")],
            unsupported_behavior=["data migration and production cutover"],
            risks=["schema evidence is incomplete without runtime and production data review"],
            validation_gates=["schema review", "data reconciliation", "rollback plan"],
            coexistence_required=True,
        ))
    waves = [
        MigrationWave(
            wave_id="wave-1",
            title="Foundation and static assets",
            unit_ids=["assets"],
            exit_criteria=["target scaffold validates"],
        ),
        MigrationWave(
            wave_id="wave-2",
            title="Routes and presentation",
            unit_ids=[unit.unit_id for unit in units if unit.unit_id.startswith("route:")],
            exit_criteria=["route checks pass", "visual review approved"],
        ),
        MigrationWave(
            wave_id="wave-3",
            title="Backend behavior and data",
            unit_ids=[unit.unit_id for unit in units if unit.unit_id.startswith("behavior:") or unit.unit_id == "data-model"],
            exit_criteria=["manual behavior work is approved", "integration tests pass", "rollback plan exists"],
        ),
    ]
    return MigrationBlueprint(
        strategy=_strategy(wesley, cir),
        target_profile="nextjs-app-router",
        units=units,
        capabilities=_capabilities(cir),
        waves=waves,
        assumptions=[
            "Static inspection is authoritative for observed source evidence only.",
            "Unsupported backend behavior is not generated automatically.",
        ],
    )
